name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    defaults:
      run:
        working-directory: ./main
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main
      - name: Checkout wrangler
        uses: actions/checkout@v2
        with:
          repository: cloudflare/wrangler
          ref: malonso/modules-do
          path: wrangler
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.49.0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 15.8.0
      - name: Install
        run: npm ci
      - name: Deploy
        run: ./wrangler.sh
